### ISSUE TITLE
Firefox / Windows reporting Trojan:AndroidOS/ZkarletFlash

### ISSUE THREAD

**Issue by SamwiseOfCat** [wheybags/EmperorLauncher#10] opened 2024-11-14 17:13 UTC
If I download the ZIP with your files in, Firefox Downloader and Windows Defender both go crazy and report a Trojan.

**Comment by wheybags** [comment] 2024-11-17 17:54
Duplicate of https://github.com/wheybags/EmperorLauncher/issues/1

**Closed as completed by wheybags** 2024-11-17 17:54 UTC
